### ISSUE TITLE
NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by teotiger** [utPLSQL/utPLSQL-cli#102]
Hey,
I downloaded latest distribution of utPLSQL-cli and tried to execute it on my local environment. I copied ojdbc8.jar as was written in README and even orai18n.jar from Oracle website to utPLSQL-cli/bin folder. However I am receiving the following error:

$ ./utplsql run devel/DEVEL@//localhost:9921/xe -p=devel -f=ut_coverage_html_reporter
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter  
        at org.utplsql.api.reporter.Reporter.setAttributes(Reporter.java:80)                 
        at org.utplsql.api.reporter.Reporter.<init>(Reporter.java:29)                        
        at org.utplsql.api.reporter.DefaultReporter.<init>(DefaultReporter.java:15)          
        at org.utplsql.api.reporter.ReporterFactory.createReporter(ReporterFactory.java:94)  
        at org.utplsql.api.reporter.ReporterFactory.create(ReporterFactory.java:122)         
        at oracle.jdbc.driver.Accessor.getORAData(Accessor.java:944)                         
        at oracle.jdbc.driver.OracleCallableStatement.getORAData(OracleCallableStatement.java:1864)                                                                                       
        at oracle.jdbc.driver.OracleCallableStatementWrapper.getORAData(OracleCallableStatementWrapper.java:789)                                                                          
        at org.utplsql.api.reporter.Reporter.initDbReporter(Reporter.java:73)                
        at org.utplsql.api.reporter.Reporter.init(Reporter.java:46)                          
        at org.utplsql.cli.reporters.LocalAssetsCoverageHTMLReporter.init(LocalAssetsCoverageHTMLReporter.java:28)                                                                        
        at org.utplsql.cli.ReporterManager.initReporters(ReporterManager.java:68)            
        at org.utplsql.cli.RunCommand.run(RunCommand.java:158)                               
        at org.utplsql.cli.Cli.main(Cli.java:33)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 14 more

$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)

My database parameters:

select * from v$version;

--
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
PL/SQL Release 11.2.0.2.0 - Production
"CORE	11.2.0.2.0	Production"
TNS for Linux: Version 11.2.0.2.0 - Production
NLSRTL Version 11.2.0.2.0 - Production

I would greatly appreciate any help or suggestions.

Thank you in advance.

**Comment by jgebal** [comment]
What version of utPLSQL do you have in database?
Can you check
 select ut.version() from dual;

**Comment by jgebal** [comment]
Aldo have a look at #99

**Comment by teotiger** [comment]
Problem solved. Installed the official Oracle Java 8. openJDK seems not to work...

**Comment by pesse** [comment]
I think we should get rid of some dependencies. Too annoying.
