### ISSUE TITLE
ORA-00001 returned before ut_coverage_html_reporter finished

### ISSUE THREAD

**Issue by hehawe** [utPLSQL/utPLSQL-cli#185]
Hi,
When I run something like
utPLSQL-cli/bin/utplsql run xxx/yyy@//zzz:1521/localpdb -c -f=ut_coverage_html_reporter -o=coverage.html
I get the following error

Successfully connected to database. UtPLSQL core: v3.1.10.3349
Oracle-Version: 18.0.0.0.0
Running tests now.
--------------------------------------
TestRunner initialized
Running on utPLSQL v3.1.10.3349
Initializing reporters
Running tests
ORA-00001: unique constraint (UT3.UT_COVERAGE_SOURCES_TMP_PK) violated
ORA-06512: at "UT3.UT_RUNNER", line 180
ORA-06512: at "UT3.UT_COVERAGE_HELPER", line 37
ORA-06512: at "UT3.UT_COVERAGE", line 166
ORA-06512: at "UT3.UT_COVERAGE", line 235
ORA-06512: at "UT3.UT_COVERAGE_HTML_REPORTER", line 35
ORA-06512: at "UT3.UT_REPORTER_BASE", line 193
ORA-06512: at "UT3.UT_EVENT_MANAGER", line 70
ORA-06512: at "UT3.UT_EVENT_MANAGER", line 80
ORA-06512: at "UT3.UT_RUN", line 74
ORA-06512: at "UT3.UT_SUITE_ITEM", line 49
ORA-06512: at "UT3.UT_RUNNER", line 172
ORA-06512: at line 1
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)

Am I doing something wrong or there's a bug?
I get the same result running ut_coverage_html_reporter in sql developer, so it's not related just to cli.

**Comment by pesse** [comment]
Can you try to uninstall and reinstall utPLSQL on your database?
Looks similar to https://github.com/utPLSQL/utPLSQL/issues/568 though this is long ago solved 🤔
@jgebal any ideas?

**Comment by jgebal** [comment]
The issue shoul be moved to utPLSQL main project

**Comment by jgebal** [comment]
This is really odd.
It seems like you have duplicate:
Owner/name/line amongst:
package body
trigger
type body
procedure
function

I didn't realize it's possible

**Comment by jgebal** [comment]
Just checked. Trigger name can overlap with package or procedure or function name.

Can you check if this is duplicated in your case?
We need a fix in utPLSQL core code to fix it.

**Comment by hehawe** [comment]
Can be at least the duplicate name identified?

I can also see the following:
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: Error : 1, Position : 0, Sql = BEGIN ut_runner.run(a_paths => :1 , a_reporters => :2 , a_color_console => (case :3  when 1 then true else false end), a_fail_on_errors => (case :4  when 1 then true else false end), a_client_character_set => :5 , a_random_test_order => (case :6  when 1 then true else false end));END;, OriginalSql = BEGIN ut_runner.run(a_paths => ?, a_reporters => ?, a_color_console => (case ? when 1 then true else false end), a_fail_on_errors => (case ? when 1 then true else false end), a_client_character_set => ?, a_random_test_order => (case ? when 1 then true else false end));END;, Error Msg = ORA-00001: unique constraint (UT3.UT_COVERAGE_SOURCES_TMP_PK) violated

**Comment by hehawe** [comment]
Even when I do just:

create or replace package testFunction_firstTest as
  --%suite(testSuite)

  --%test
  procedure firstTest;
end;
/
create or replace package body testFunction_firstTest as
    procedure firstTest
    is
    begin
        ut.expect( 1 ).to_equal( 1 );
    end;
end;
/

I got the same error
