### ISSUE TITLE
Changing failure code does not work  "-fcode=0"

### ISSUE THREAD

**Issue by clarkec21** [utPLSQL/utPLSQL-cli#214]
Hi
I am calling utplsql-cli via GitHub Actions on a runner server on OCI as ADMIN user. I pass in multiple schemas to be processed and am writing the documentation to a file and coverage html to a file.   In an attempt to get around an issue with ONS (https://github.com/utPLSQL/utPLSQL-cli/issues/213) I added -fcode="0" and encountered errors:

```
java.sql.SQLException: ORA-06550: line 1, column 13:
PLS-00201: identifier 'CODE0' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
        at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
        at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
        at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
        at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
        at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
        at org.utplsql.api.reporter.Reporter.initDbReporter(Reporter.java:72)
        at org.utplsql.api.reporter.Reporter.init(Reporter.java:46)
        at org.utplsql.cli.ReporterManager.initReporters(ReporterManager.java:95)
        at org.utplsql.cli.RunAction.initReporters(RunAction.java:222)
        at org.utplsql.cli.RunAction.doRun(RunAction.java:71)
        at org.utplsql.cli.RunAction.run(RunAction.java:122)
        at org.utplsql.cli.RunPicocliCommand.run(RunPicocliCommand.java:265)
        at org.utplsql.cli.Cli.runPicocliWithExitCode(Cli.java:47)
        at org.utplsql.cli.Cli.main(Cli.java:17)
Caused by: Error : 6550, Position : 12, Sql = BEGIN :1 := CODE0(); END;, OriginalSql = {? = call CODE0()}, Error Msg = ORA-06550: line 1, column 13:
PLS-00201: identifier 'CODE0' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
```
However when using --failure-exit-code="0" I get no such error

**Comment by jgebal** [comment]
Hi @clarkec21 
Thank you for reporting this issue and sorry for late reply.
@pesse - would you be able to look into it?

**Comment by clarkec21** [comment]
Hi @jgebal thank you for replying.
