### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/nio/zipfs/ZipPath

### ISSUE THREAD

**Issue by walter-weinmann** [utPLSQL/utPLSQL-cli#99]
`CALL utPLSQL-cli_3.1.0\bin\utplsql.bat run %USERNAME_UT%/%PASSWORD_UT%@%NET_SERVICE_NAME% -c -f=ut_coverage_html_reporter -o=test\wwe.html -f=ut_documentation_reporter -p=%USERNAME_DBSS% -source_path=src/packages -test_path=test/packages`

gives me:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/nio/zipfs/ZipPath
        at org.utplsql.api.ResourceUtil.getListOfChildren(ResourceUtil.java:61)
        at org.utplsql.api.reporter.CoverageHTMLReporter.writeReportAssetsTo(CoverageHTMLReporter.java:104)
        at org.utplsql.cli.reporters.LocalAssetsCoverageHTMLReporter.init(LocalAssetsCoverageHTMLReporter.java:31)
        at org.utplsql.cli.ReporterManager.initReporters(ReporterManager.java:68)
        at org.utplsql.cli.RunCommand.run(RunCommand.java:158)
        at org.utplsql.cli.Cli.main(Cli.java:33)
Caused by: java.lang.ClassNotFoundException: com.sun.nio.zipfs.ZipPath
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 6 more

```

and an empty directory here:

![image](https://user-images.githubusercontent.com/1956149/45278862-38dc6d00-b4cf-11e8-96d9-8a0819769cce.png)

**Comment by pesse** [comment]
Hi @walter-weinmann, I guess you use Java 9+
Please use Java 8 instead.
We will probably have a Java 9+ compatible version in future but from that time we'll have to maintain two separate branches.

**Comment by walter-weinmann** [comment]
Thanks for the help - I've switched back - now it is ok.
